// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjBBkEDnsaObQmfW8eSdtdddV3GH-L9m4',
    appId: '1:221195809668:android:8c6da223e37dc061b7e3d1',
    messagingSenderId: '221195809668',
    projectId: 'houra-f9a61',
    storageBucket: 'houra-f9a61.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlbtD6QDtrkfwGCYJn8WlCWd9jq7A2Zo',
    appId: '1:221195809668:ios:892b0caef2c8062ab7e3d1',
    messagingSenderId: '221195809668',
    projectId: 'houra-f9a61',
    storageBucket: 'houra-f9a61.firebasestorage.app',
    iosBundleId: 'com.example.houraApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALc2Lll_ecAZA6gO4onTFayPrwrdVcZQ',
    appId: '1:221195809668:web:fca558afab918fffb7e3d1',
    messagingSenderId: '221195809668',
    projectId: 'houra-f9a61',
    authDomain: 'houra-f9a61.firebaseapp.com',
    storageBucket: 'houra-f9a61.firebasestorage.app',
    measurementId: 'G-NPY7LBSRCM',
  );
}
